{{- if .Values.ingress.enabled }}
apiVersion: {{ include "ingress.apiVersion" . }} 
kind: Ingress
metadata:
  name: {{ include "names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "labels.standard" . | nindent 4 }}
{{- if .Values.ingress.annotations }}
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
{{- end }}
spec:
  {{- if and .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          {{- if .Values.ingress.extraPaths }}
          {{- toYaml .Values.ingress.extraPaths | nindent 10 }}
          {{- end }}
          - path: {{ .Values.ingress.path }}
            {{- if eq "true" (include "ingress.supportsPathType" .) }}
            pathType: {{ .Values.ingress.pathType }}
            {{- end }}
            backend: 
              service:
                name: {{ include "names.fullname" . }}
                port:
                  number: {{ .Values.service.targetPort }}
    {{- end }}
    {{- range .Values.ingress.extraHosts }}
    - host: {{ .name | quote }}
      http:
        paths:
          - path: {{ default "/" .path }}
            {{- if eq "true" (include ".ingress.supportsPathType" $) }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            {{- end }}
            backend: 
              service:
                name: {{ include "names.fullname" . }}
                port:
                  number: {{ .Values.service.targetPort }}
            
    {{- end }}
  {{- if or .Values.ingress.tls (include "ingress.certManagerRequest" ( dict "annotations" .Values.ingress.annotations ))  }}
  tls:
    {{- if include "ingress.certManagerRequest" ( dict "annotations" .Values.ingress.annotations )  }}
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
    {{- end }}
    {{- if .Values.ingress.tls }}
    {{-  toYaml .Values.ingress.tls | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
