{{- if not .Values.existingSecret  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "labels.standard" . | nindent 4 }}
type: Opaque
data:
  portfolioSuperUserPassword: {{ .Values.portfolioSuperUserPassword | b64enc  | default (include "secret.generatePassword" . ) | quote }}
  {{- if .Values.configMail }}
  emailPassword: {{ .Values.configMail.hostPassword | b64enc | quote }}
  {{- end }}
{{- end }}
