apiVersion: v2
name: porfolio
description: A Helm chart for portfolio of hmei28

type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
